github.com:
    users:
        srgubayjdullina:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: srgubayjdullina
